export const ADD_PROPERTIES = "ADD_PROPERTIES";
export const SELECTED_PROPERTY = "SELECTED_PROPERTY";
export const PROPERTY_MAP = "PROPERTY_MAP";
export const FILTERED_PROPERTIES = "FILTERED_PROPERTIES";
export const FILTERS = "FILTERS";